---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "11.18.6"
  environments_path: ../../test/environments
  roles_path: ../../test/roles

platforms:
  - name: centos65
    driver:
      box: centos65
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
  - name: sentinel_service
    provisioner:
      solo_rb:
        environment: flume_agent_test
    run_list:
      - role[flume_agent_role]
      - minitest-handler::default